trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: BCDR  # The name of the repository resource
      type: git
      name: BCDR  # The name of your Azure DevOps repository
      ref: main  # The branch from which you want to pick the file (main in this case)

steps:
- checkout: self
  persistCredentials: true
  clean: true

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'LinkTech-Prod-Sub'  # Replace with the name of your Azure service connection.
    subscriptionId: 'c23271e6-01ae-4dfa-85d3-783bf6dfa210'  # Replace with your Azure subscription ID.
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'azcc-prd-spk-LinkTech-RG'  # Replace with the name of the resource group you want to create or update.
    location: 'Canada Central'  # Replace with your desired Azure region.
    templateLocation: 'Linked artifact'
    csmFile: '$(Pipeline.Workspace)/BCDR/template.json'  # The path to the template.json file in the BCDR repository
    deploymentMode: 'Incremental'  # Change to 'Complete' if you want to overwrite the resource group.
